model_list:
  - model_name: ollama
    litellm_params:
        model: ollama/llama3
        api_base: http://localhost:11434
        api_key: <Your Key>

general_settings: 
  master_key: <Your Key>
  database_url: "postgres://user:password@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres" # 👈 KEY CHANGE

# Test
# ====
# curl --location 'http://0.0.0.0:4000/chat/completions' \
# --header 'Content-Type: application/json' \
# --header 'Authorization: Bearer <Your Key>' \
# --data ' {
#       "model": "ollama",
#       "messages": [
#         {
#           "role": "user",
#           "content": "what llm are you"
#         }
#       ]
#     }
# '
