name: Checkout

on: [push]

jobs:
  # Checkout Action Job
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      - name: Checkout
        uses: actions/checkout@v3 # Checkout the repository
      - name: List Files After
        run: ls -a

  # Checkout and Display Files Job
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
          git fetch origin
          git checkout main
      - name: List Files After
        run: ls -a
